### PR TITLE
Add Fuchsia to the list

### PR DESCRIPTION
**Pull request by rtsuk**
Fuchsia is a new open source operating system under development at Google. It supports only Vulkan for hardware accelerated graphics at the moment, so I am starting to try to get Vulkano running on it.

This PR adds Fuchsia to the list. All tests pass.

This PR also adds license files matching the license claims in Cargo.toml. Google requires such files to exist to allow me, as a Google employee, to submit patches.

### CODE REVIEW

**Comment by tomaka** [comment]
Is it normal that the license files are empty?

**Comment by rtsuk** [comment]
No, I just forgot to hit save in TextMate.

Let me know if you want something different in the MIT license file.

**Comment by tomaka** [comment]
It's good, thanks!

**Comment by tomaka** [comment]
(by the way let me know if you need help with vulkano)

**Pull request merged**
